name: scheduled_date_picker
description: A new Flutter package project.
version: 1.0.0
homepage: https://github.com/ViniciusSossela/scheduled-date-picker

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.16.1


dev_dependencies:
  flutter_test:
    sdk: flutter
