name: scheduled_date_picker
description: The scheduled date picker is a set of widgets that allows scheduling date. This can be useful in many scenarios, for scheduled tasks for example.
version: 1.0.4
author: Vinicius T. Sossella <viniciussossella@gmail.com>
homepage: https://github.com/ViniciusSossela/scheduled-date-picker

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.16.1


dev_dependencies:
  flutter_test:
    sdk: flutter
